### ISSUE TITLE
Package is invalid. Details: 'Could not load background script 'background.js'.'

### ISSUE THREAD

**Issue by AlexLog** [bfred-it/sticky-pinned-tabs#1]
Package is invalid. Details: 'Could not load background script 'background.js'.'

macOS 10.12.1, Chrome 55.0.2883.87

**Comment by fregante** [comment]
Do you have this issue when loading this repo or when you download it from the Chrome Store?

If you use this repo you'll have to run `npm install` and `npm run build` first

**Comment by AlexLog** [comment]
Chrome Store, I did not try the repo

**Comment by madmuffin1** [comment]
I have the same problem, though the message states content.js instead of background.js.
Chrome 57

**Comment by stoe** [comment]
> I have the same problem, though the message states content.js instead of background.js.

Same, Chrome 58

**Comment by fregante** [comment]
Sorry about this, guys. It's fixed now. It was a borked upload. 1.1.5 should work (when the Web Store makes it public)
